name: dgcd
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.2.25=h06a4308_0
  - expat=2.6.4=h6a678d5_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.16=h5eee18b_0
  - pip=25.0=py312h06a4308_0
  - python=3.12.9=h5148396_0
  - readline=8.2=h5eee18b_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - xz=5.6.4=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - absl-py==2.1.0
      - accelerate==1.10.0
      - aiohttp==3.9.5
      - aiosignal==1.3.1
      - annotated-types==0.7.0
      - asttokens==2.4.1
      - attrs==23.2.0
      - bleach==6.2.0
      - blis==1.2.0
      - cachetools==5.5.0
      - catalogue==2.0.10
      - certifi==2024.2.2
      - cffi==1.17.1
      - charset-normalizer==3.3.2
      - click==8.1.7
      - clip==1.0
      - cloudpathlib==0.21.0
      - comm==0.2.2
      - confection==0.1.5
      - contourpy==1.2.1
      - controlnet-aux==0.0.10
      - cycler==0.12.1
      - cymem==2.0.11
      - cython==0.29.37
      - datasets==2.19.1
      - debugpy==1.8.1
      - decorator==5.1.1
      - diffusers==0.34.0
      - dill==0.3.8
      - docker-pycreds==0.4.0
      - docstring-parser==0.16
      - easydict==1.13
      - einops==0.8.0
      - et-xmlfile==1.1.0
      - executing==2.0.1
      - fastai==2.7.19
      - fastcore==1.7.29
      - fastdownload==0.0.7
      - fastprogress==1.0.3
      - filelock==3.14.0
      - flatbuffers==25.2.10
      - fonttools==4.51.0
      - frozenlist==1.4.1
      - fsspec==2024.3.1
      - ftfy==6.2.0
      - fvcore==0.1.6
      - geoopt==0.5.1
      - gitdb==4.0.11
      - gitpython==3.1.43
      - grad-cam==1.5.5
      - grpcio==1.65.4
      - hdbscan==0.8.37
      - hf-xet==1.1.7
      - higher==0.2.1
      - huggingface-hub==0.34.4
      - idna==3.7
      - imageio==2.37.0
      - importlib-metadata==6.11.0
      - iopath==0.1.10
      - ipykernel==6.29.4
      - ipython==8.24.0
      - jax==0.7.0
      - jaxlib==0.7.0
      - jedi==0.19.1
      - jinja2==3.1.4
      - joblib==1.4.2
      - jupyter-client==8.6.1
      - jupyter-core==5.7.2
      - kaggle==1.7.4.5
      - kagglehub==0.3.13
      - kiwisolver==1.4.5
      - langcodes==3.5.0
      - language-data==1.3.0
      - lazy-loader==0.4
      - lightning-utilities==0.15.2
      - llvmlite==0.43.0
      - loguru==0.7.3
      - lpips==0.1.4
      - marisa-trie==1.2.1
      - markdown==3.6
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.9.0
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - mediapipe==0.10.21
      - ml-dtypes==0.5.3
      - mpmath==1.3.0
      - multidict==6.0.5
      - multiprocess==0.70.16
      - murmurhash==1.0.12
      - nest-asyncio==1.6.0
      - networkx==3.3
      - ninja==1.11.1.1
      - numba==0.60.0
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-ml-py==12.535.161
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.1.105
      - nvitop==1.3.2
      - openai-clip==1.0.1
      - opencv-contrib-python==4.11.0.86
      - opencv-python==4.11.0.86
      - opencv-python-headless==4.12.0.88
      - openpyxl==3.1.4
      - opt-einsum==3.4.0
      - packaging==24.0
      - pandas==2.2.2
      - parso==0.8.4
      - pexpect==4.9.0
      - pillow==10.3.0
      - platformdirs==4.2.2
      - portalocker==3.1.1
      - preshed==3.0.9
      - prompt-toolkit==3.0.43
      - protobuf==4.25.8
      - psutil==5.9.8
      - ptflops==0.7.5
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pyarrow==16.1.0
      - pyarrow-hotfix==0.6
      - pycparser==2.22
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pygments==2.18.0
      - pynndescent==0.5.13
      - pyparsing==3.1.2
      - pysocks==1.7.1
      - python-dateutil==2.9.0.post0
      - python-slugify==8.0.4
      - pytz==2024.1
      - pyyaml==6.0.1
      - pyzmq==26.0.3
      - ranger==0.10
      - ranger-fm==1.9.3
      - regex==2024.5.15
      - requests==2.31.0
      - rich==13.7.1
      - safetensors==0.4.3
      - scikit-image==0.25.2
      - scikit-learn==1.6.1
      - scipy==1.13.0
      - seaborn==0.13.2
      - sentencepiece==0.2.0
      - sentry-sdk==2.12.0
      - setproctitle==1.3.3
      - setuptools==69.5.1
      - shellingham==1.5.4
      - shtab==1.7.1
      - six==1.16.0
      - smart-open==7.1.0
      - smmap==5.0.1
      - sounddevice==0.5.2
      - spacy==3.8.4
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - srsly==2.5.1
      - stack-data==0.6.3
      - sympy==1.12
      - tabulate==0.9.0
      - tensorboard==2.17.0
      - tensorboard-data-server==0.7.2
      - termcolor==2.4.0
      - text-unidecode==1.3
      - thinc==8.3.4
      - thop==0.1.1-2209072238
      - threadpoolctl==3.5.0
      - tifffile==2025.3.30
      - timm==1.0.3
      - tokenizers==0.21.4
      - torch==2.4.1
      - torchaudio==2.6.0+cu126
      - torchinfo==1.8.0
      - torchmetrics==1.8.2
      - torchprofile==0.0.4
      - torchvision==0.19.1
      - tornado==6.4
      - tqdm==4.66.4
      - traitlets==5.14.3
      - transformers==4.55.2
      - triton==3.0.0
      - trl==0.8.6
      - ttach==0.0.3
      - typer==0.15.2
      - typing-extensions==4.13.0
      - tyro==0.8.4
      - tzdata==2024.1
      - umap==0.1.1
      - umap-learn==0.5.7
      - urllib3==2.2.1
      - wandb==0.17.6
      - wasabi==1.1.3
      - wcwidth==0.2.13
      - weasel==0.4.1
      - webencodings==0.5.1
      - werkzeug==3.0.3
      - wheel==0.43.0
      - wrapt==1.17.2
      - xformers==0.0.28.post1
      - xlsxwriter==3.2.0
      - xxhash==3.4.1
      - yacs==0.1.8
      - yarl==1.9.4
      - zipp==3.18.2
prefix: /users/student/pg/pg23/vaibhav.rathore/.conda/envs/dgcd
